version: 2

models:
  - name: stg_ventes
    columns:
      - name: produit_id
        tests:
          - not_null
          - unique

  - name: stg_avis
    columns:
      - name: produit_id
        tests:
          - not_null
          - unique

  - name: stg_activite
    columns:
      - name: produit_id
        tests:
          - not_null
          - unique